services:
  # Database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Django web application
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ecommerce
      - ALLOWED_HOSTS=localhost,127.0.0.1
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
